### ISSUE TITLE
Recent changes to geogebra.org/GeoGebraTube seem to be breaking the plugin

### ISSUE THREAD

**Issue by avohns** [mebis-lp/moodle-qtype_geogebra#8]
We have been using the GeoGebra question type plugin for moodle for a while. There seems to be a problem caused by recent changes in GeoGebraTube which seem to be breaking or at least causing serious problems with this question type:

Any question text that should normally show up before the GeoGebra-Applet ist rendered invisible (there seems to be a problem where a "visibility:hidden" tag is not properly overwritten).
While the applet itself is still loading, it is rendered "below" other objects on the page, in other words: the necesarry space is somehow not being reserved by the plugin (a workaround is to change the brwoser window size).
We have tested this behaviour in two different moodle installations, none of which had any general updates or updates of the question type plugin so our only explanation at the moment is that some error in the communication between the plugin and GeoGebra (the plugin loads GeoGebra dynamically from geogebra.org).

Anyone else who noticed thios problem? Any possible solutions?

**Comment by PM84** [comment]
Does the problem still exist?

**Comment by josejulian0727** [comment]
Hi Peter.
Problems still, im working moodle 3.11 (3.10 too) and the recently released Geogebra plug (moodle-qtype_geogebra-MOODLE_311_STABLE), but there are no changes.
Thanks.
![Captura1](https://user-images.githubusercontent.com/86481171/123501406-4a547c80-d60a-11eb-9375-61f54c6e1cc0.JPG)

**Comment by PM84** [comment]
Have you purged the caches after upgradeing? Especially the js and css caches?

Which Theme do you use?

**Comment by josejulian0727** [comment]
Hi Peter. 
Thanks for your answer, I did the corresponding procedures, but the problems are still occurring.
Theme in Moodle (3.11) is Boost.
Thks!

**Comment by Bejagui** [comment]
Hi All.

In fact, I would like to take advantage of this message to say about 3 problems:

1.- Like José Julián, I have the same situation.  I have always solve the problem decribing the instructions into GeoGebra enviroment; but this is a problem because the visualitation isn't good

2.- When I use random sliders, the students solve the question. Bur when they or me want review, random sliders continue in active form and solution of students is showed correctly, but the conditions are new; so it is impossible to know why the student answer was wrong.

3.- The documentation is poor, or is not easily accesible. (Maybe this is only my problem). So please, send me a link where I can learn about this plugin.

In other foro I read:     "Sorry, we're not supporting this plugin any more. "
and this other:  "The mebis-Bayern team has decided to continue maintaining this plugin. "

Please, don't leave this project. Your plugin is beautifull and very important.   Don't put in your possibles "abandoned projects list" this plugin. Never please.

**Comment by josejulian0727** [comment]
Hi Peter.
The environment improved too much, but the variables still keep changing when the result is checked. I followed the documentation step by step creating the questions in GogebraTube, copy and paste the link in moodle. This plugin is a powerful tool that we teachers implement in our classrooms. Thank you for the effort and I hope you do not give up.
Regards.

![image](https://user-images.githubusercontent.com/86481171/123696814-cd9beb00-d821-11eb-8ea7-3995dc0de71c.png)

**Comment by PM84** [comment]
I added a new Commit to the branche above. Please try again :-) (I've no other opportunity, because up to now, I was not able to reproduce the error)
